// Copyright 2023 S44, LLC
// Copyright Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache 2.0

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { AuthorizationStatusEnumType16 } from '../enums';
import { OcppResponse } from '../../..';

export interface AuthorizeResponse16 extends OcppResponse {
  idTagInfo: IdTagInfoType16;
}
export interface IdTagInfoType16 {
  expiryDate?: string | null;
  parentIdTag?: string | null;
  status: AuthorizationStatusEnumType16;
}
