// Copyright 2023 S44, LLC
// Copyright Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache 2.0

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { OcppResponse } from '../../..';

export interface GetConfigurationResponse16 extends OcppResponse {
  configurationKey?: KeyValueType16[] | null;
  unknownKey?: string[] | null;
}
export interface KeyValueType16 {
  key: string;
  readonly: boolean;
  value?: string | null;
}
