// Copyright 2023 S44, LLC
// Copyright Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache 2.0

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {
  GetCompositeScheduleStatusEnumType16,
  ChargingRateUnitTypeEnumType16,
} from '../enums';
import { OcppResponse } from '../../..';

export interface GetCompositeScheduleResponse16 extends OcppResponse {
  status: GetCompositeScheduleStatusEnumType16;
  connectorId?: number | null;
  scheduleStart?: string | null;
  chargingSchedule?: ChargingScheduleType16 | null;
}
export interface ChargingScheduleType16 {
  duration?: number | null;
  startSchedule?: string | null;
  chargingRateUnit: ChargingRateUnitTypeEnumType16;
  chargingSchedulePeriod: ChargingScheduleType16Period[];
  minChargingRate?: number | null;
}
export interface ChargingScheduleType16Period {
  startPeriod: number;
  limit: number;
  numberPhases?: number | null;
}
