// Copyright 2023 S44, LLC
// Copyright Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache 2.0

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { AuthorizationStatusEnumType16, UpdateTypeEnumType16 } from '../enums';
import { OcppRequest } from '../../..';

export interface SendLocalListRequest16 extends OcppRequest {
  listVersion: number;
  localAuthorizationList?: AuthorizationDataType16[] | null;
  updateType: UpdateTypeEnumType16;
}
export interface AuthorizationDataType16 {
  idTag: string;
  idTagInfo?: IdTagInfoType16 | null;
}
export interface IdTagInfoType16 {
  expiryDate?: string | null;
  parentIdTag?: string | null;
  status: AuthorizationStatusEnumType16;
}
