// Copyright 2023 S44, LLC
// Copyright Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache 2.0

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {
  ChargingProfilePurposeTypeEnumType16,
  ChargingProfileKindTypeEnumType16,
  RecurrencyKindTypeEnumType16,
  ChargingRateUnitTypeEnumType16,
} from '../enums';
import { OcppRequest } from '../../..';

export interface SetChargingProfileRequest16 extends OcppRequest {
  connectorId: number;
  csChargingProfiles: ChargingProfileType16;
}
export interface ChargingProfileType16 {
  chargingProfileId: number;
  transactionId?: number | null;
  stackLevel: number;
  chargingProfilePurpose: ChargingProfilePurposeTypeEnumType16;
  chargingProfileKind: ChargingProfileKindTypeEnumType16;
  recurrencyKind?: RecurrencyKindTypeEnumType16 | null;
  validFrom?: string | null;
  validTo?: string | null;
  chargingSchedule: ChargingScheduleType16;
}
export interface ChargingScheduleType16 {
  duration?: number | null;
  startSchedule?: string | null;
  chargingRateUnit: ChargingRateUnitTypeEnumType16;
  chargingSchedulePeriod: ChargingScheduleType16Period[];
  minChargingRate?: number | null;
}
export interface ChargingScheduleType16Period {
  startPeriod: number;
  limit: number;
  numberPhases?: number | null;
}
