// Copyright 2023 S44, LLC
// Copyright Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache 2.0

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {
  ReasonEnumType16,
  ReadingContextEnumType16,
  ValueFormatEnumType16,
  MeasurandEnumType16,
  PhaseEnumType16,
  LocationEnumType16,
  UnitOfMeasureEnumType16,
} from '../enums';
import { OcppRequest } from '../../..';

export interface StopTransactionRequest16 extends OcppRequest {
  idTag?: string | null;
  meterStop: number;
  timestamp: string;
  transactionId: number;
  reason?: ReasonEnumType16 | null;
  transactionData?: MeterValueType16[] | null;
}
export interface MeterValueType16 {
  timestamp: string;
  sampledValue: SampledValueType16[];
}
export interface SampledValueType16 {
  value: string;
  context?: ReadingContextEnumType16 | null;
  format?: ValueFormatEnumType16 | null;
  measurand?: MeasurandEnumType16 | null;
  phase?: PhaseEnumType16 | null;
  location?: LocationEnumType16 | null;
  unit?: UnitOfMeasureEnumType16 | null;
}
